import React from 'react';
import Modal from '../common/Modal';
import { usePMSStore } from '../../store/usePMSStore';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faPrint,
  faDownload,
  faBuildingCircleCheck,
  faCircleCheck,
  faReceipt,
  faBarcode
} from '@fortawesome/free-solid-svg-icons';

export default function PaymentReceiptModal({ isOpen, onClose, payment }) {
  const { settings } = usePMSStore();

  if (!payment) return null;

  const handlePrint = () => {
    window.print();
  };

  const baseRent = Math.round(payment.amount * 0.95);
  const taxes = Math.round(payment.amount * 0.05);

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Official Payment Receipt"
      subtitle={`Receipt Reference: ${payment.invoiceNumber}`}
      maxWidth="max-w-xl"
      footer={
        <div className="flex items-center justify-between w-full no-print">
          <span className="text-[11px] text-slate-400">
            Official receipt generated by {settings.companyName}
          </span>
          <div className="flex items-center gap-2">
            <button
              onClick={onClose}
              className="px-4 py-2 text-xs font-semibold text-slate-700 bg-white border border-slate-300 rounded-xl hover:bg-slate-50"
            >
              Close
            </button>
            <button
              onClick={handlePrint}
              className="px-4 py-2 text-xs font-bold text-white bg-slate-900 hover:bg-black rounded-xl shadow-xs flex items-center gap-1.5"
            >
              <FontAwesomeIcon icon={faPrint} />
              Print Receipt
            </button>
          </div>
        </div>
      }
    >
      <div id="printable-area" className="p-4 sm:p-6 bg-white text-slate-900 space-y-6 text-left text-xs">
        {/* Company Header */}
        <div className="flex items-start justify-between border-b border-slate-200 pb-5">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-600 text-white flex items-center justify-center shadow-xs">
              <FontAwesomeIcon icon={faBuildingCircleCheck} className="text-xl" />
            </div>
            <div>
              <h2 className="text-base font-extrabold text-slate-900 leading-tight">
                {settings.companyName}
              </h2>
              <p className="text-[11px] text-slate-500">{settings.hqAddress}</p>
              <p className="text-[10px] text-slate-400">
                Tax Reg: {settings.taxRegistrationNumber} • {settings.supportEmail}
              </p>
            </div>
          </div>

          <div className="text-right">
            <span className="inline-block px-2.5 py-1 rounded-full bg-emerald-50 text-emerald-700 font-extrabold text-xs border border-emerald-200">
              OFFICIAL RECEIPT
            </span>
            <p className="text-xs font-bold text-slate-800 mt-1">{payment.invoiceNumber}</p>
            <p className="text-[11px] text-slate-500">Date: {payment.paymentDate || payment.dueDate}</p>
          </div>
        </div>

        {/* Billed To & Property Spec */}
        <div className="grid grid-cols-2 gap-4 bg-slate-50 p-4 rounded-xl border border-slate-200/80">
          <div>
            <span className="text-[10px] uppercase font-bold tracking-wider text-slate-400 block mb-1">
              Received From (Tenant)
            </span>
            <p className="font-extrabold text-slate-900 text-sm">{payment.customerName}</p>
            <p className="text-slate-600 mt-0.5">
              Unit {payment.unitNumber}, {payment.propertyName}
            </p>
          </div>

          <div>
            <span className="text-[10px] uppercase font-bold tracking-wider text-slate-400 block mb-1">
              Payment Information
            </span>
            <p className="font-semibold text-slate-800">
              Method: <strong>{payment.method}</strong>
            </p>
            <p className="text-slate-600">
              Ref: <span className="font-mono">{payment.referenceNumber || 'INTERNAL-RECORD'}</span>
            </p>
            <p className="text-emerald-700 font-bold flex items-center gap-1 mt-0.5">
              <FontAwesomeIcon icon={faCircleCheck} className="text-xs" /> Status: {payment.status}
            </p>
          </div>
        </div>

        {/* Items Table */}
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="border-b border-slate-200 text-[11px] uppercase tracking-wider text-slate-500 font-bold">
              <th className="py-2.5">Item Description</th>
              <th className="py-2.5 text-right">Allocation</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100 text-xs">
            <tr>
              <td className="py-3 font-semibold text-slate-800">
                {payment.notes || 'Monthly Rent Settlement'}
                <span className="block text-[10px] text-slate-400">Period: Current Billing Cycle</span>
              </td>
              <td className="py-3 text-right font-medium text-slate-900">
                QAR {baseRent.toLocaleString()}
              </td>
            </tr>
            <tr>
              <td className="py-2.5 text-slate-600">Municipal Services & Utility Assessment</td>
              <td className="py-2.5 text-right font-medium text-slate-900">
                QAR {taxes.toLocaleString()}
              </td>
            </tr>
          </tbody>
          <tfoot>
            <tr className="border-t-2 border-slate-900">
              <td className="py-3 text-sm font-extrabold text-slate-900">Total Amount Settled:</td>
              <td className="py-3 text-right text-base font-extrabold text-emerald-700">
                QAR {payment.amount.toLocaleString()}
              </td>
            </tr>
          </tfoot>
        </table>

        {/* Corporate Sign-off & Barcode */}
        <div className="pt-4 border-t border-slate-200 flex items-center justify-between">
          <div>
            <div className="inline-block p-2 border-2 border-emerald-600 rounded-lg text-emerald-700 text-center uppercase tracking-widest font-extrabold text-[10px] transform -rotate-3">
              ★ SETTLED & VERIFIED ★<br />
              APEX INTERNAL PORTAL
            </div>
            <p className="text-[9px] text-slate-400 mt-2">
              Payment verified by Corporate Finance Operations.
            </p>
          </div>

          <div className="text-right">
            <FontAwesomeIcon icon={faBarcode} className="text-3xl text-slate-700 block ml-auto" />
            <span className="font-mono text-[9px] text-slate-400 block mt-0.5">
              {payment.invoiceNumber}-{payment.id}
            </span>
          </div>
        </div>
      </div>
    </Modal>
  );
}
